---
development:
  cloud_name: speakit
  api_key: '393565828363517'
  api_secret: 19skAahNYdGiafW_M77Wb_LP2-U
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: speakit
  api_key: '393565828363517'
  api_secret: 19skAahNYdGiafW_M77Wb_LP2-U
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: speakit
  api_key: '393565828363517'
  api_secret: 19skAahNYdGiafW_M77Wb_LP2-U
  enhance_image_tag: true
  static_file_support: false
